[IV-22-23] Objetivo 3
vdeq79/Projecto-XSZ pull request #11
Opened 2022-10-31 15:06 UTC by vdeq79

* [ ]  ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ]  ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ]  ¿Ese issue está asignado a un milestone?
* [ ]  ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ]  ¿El PR, que también es un issue, está asignado al mismo milestone?

2022-11-01 08:56 UTC, JJ commented
¿Qué tiene que ver la comprobación de la sintaxis con la librería para extraer datos? Mira, por favor, los errores frecuentes incluidos en la semana 8.

2022-11-01 09:35 UTC, vdeq79 commented
> ¿Qué tiene que ver la comprobación de la sintaxis con la librería para extraer datos? Mira, por favor, los errores frecuentes incluidos en la semana 8.

De acuerdo, no lo tenía pensado.  De primeras, la comprobación de la sintaxis servirá para comprobar que las estructuras de datos no tengan errores.

2022-11-01 10:33 UTC, JJ commented
> > ¿Qué tiene que ver la comprobación de la sintaxis con la librería para extraer datos? Mira, por favor, los errores frecuentes incluidos en la semana 8.
> 
> De acuerdo, no lo tenía pensado. De primeras, la comprobación de la sintaxis servirá para comprobar que las estructuras de datos no tengan errores.

Y eso ¿a qué milestone corresponde?

Os agradecería que pensárais, antes de hacer algo "porque se pide", la razón por la que se pide y los conceptos y buenas prácticas que hay detrás.

2022-11-01 10:42 UTC, vdeq79 commented
> 



> > > ¿Qué tiene que ver la comprobación de la sintaxis con la librería para extraer datos? Mira, por favor, los errores frecuentes incluidos en la semana 8.
> > 
> > 
> > De acuerdo, no lo tenía pensado. De primeras, la comprobación de la sintaxis servirá para comprobar que las estructuras de datos no tengan errores.
> 
> Y eso ¿a qué milestone corresponde?
> 
> Os agradecería que pensárais, antes de hacer algo "porque se pide", la razón por la que se pide y los conceptos y buenas prácticas que hay detrás.

Entiendo que es en M0 como he señalado, serviría para comprabar las estructuras de datos resultantes de dicho milestone.

2022-11-03 12:48 UTC, JJ requested changes
Trata de poner los criterios que has seguido para buscar, probar diferentes opciones y poner claramente el proceso de decisión seguido.

2022-11-03 12:48 UTC, JJ commented on .eslintignore
> +node_modules
Esto no corresponde a este milestone.

2022-11-03 12:48 UTC, JJ commented on README.md
> +Apartir de la lista de animes proporcionado por el usuario, aplicando el algoritmo de conjuntos frecuentes se generará una lista de animes no vistos que se aproxime a las preferencias del usuario.
Por favor, hacedlo en un PR aparte.

2022-11-04 09:21 UTC, vdeq79 commented
Listo para revisión @JJ .

2022-11-07 14:15 UTC, JJ requested changes
Mira [estos errores frecuentes](https://github.com/JJ/IV-22-23/blob/master/sesiones/semana-08.md#objetivo-3), especialmetne el último.

2022-11-07 16:56 UTC, vdeq79 commented
Listo para revisión @JJ. En este caso, puesto que el objetivo 2 no está todavía acabado y no está creada la carpeta src, al ejecutar la orden tal como está el repositorio daría error. Pero he probado la orden en mi máquina local y he visto que efectivamente funciona.

2022-11-07 17:19 UTC, JJ requested changes
Consulta los errores frecuentes, tanto el indicado como el de esta semana. Buen trabajo de todas formas en la comparación.

2022-11-07 17:19 UTC, JJ commented on docs/documentations/gestor-de-dependencias.md
> +De cara a la elección del gestor de dependencias, estas son algunas de las posibilidades:
Ya lo puse el jueves/viernes pasado, pero se ve que hay que [deciros personalmente que consultéis los errores frecuentes](https://github.com/JJ/IV-22-23/blob/master/sesiones/semana-08.md#objetivo-3).

2022-11-10 12:36 UTC, vdeq79 commented
Listo para revision @JJ.

2022-11-10 13:28 UTC, vdeq79 commented
Tras lo que me dijiste en clase, he realizado el cambio. Listo para revisión @JJ.

2022-11-10 19:00 UTC, JJ approved these changes
:+1:

2022-11-11 08:04 UTC, merged