[IV 22-23] Objetivo 2
vdeq79/Projecto-XSZ pull request #14
Opened 2022-11-03 18:21 UTC by dmonjasm

* [X] ¿He seguido las mejores prácticas en nombre de las clases y ficheros y
   disposición de los mismos?
* [X] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [X] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [X] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.
* [X] ¿Los issues representan un problema, y no una tarea?
* [X] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [X] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [X] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [X] ¿Todos los issues creados están asignados a una HU?
* [X] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit? Los issues sobre los que estoy trabajando, ¿han
      sido asignados al primer milestone?
* [X] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [X] ¿Son los milestones sobre los que estoy trabajando productos
   mínimamente viables? ¿O tengo que solicitar al product manager que
   cree milestones adicionales o precise de qué producto se trata?
* [X] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

2022-11-03 18:27 UTC, dmonjasm commented
Necesito que asignes el [M0] al PR para que pase los tests

2022-11-03 18:27 UTC, dmonjasm commented
@vdeq79

2022-11-03 18:29 UTC, vdeq79 commented
Creo que deberías de eliminar los archivos generados.

2022-11-03 18:31 UTC, dmonjasm commented
Cierto, se me olvidó cuando probé que compilaban.

2022-11-03 18:51 UTC, dmonjasm commented
No sé si quieres añadir o perfilar algo más o abrir algún issue extra @vdeq79.

2022-11-03 18:59 UTC, vdeq79 commented
> No sé si quieres añadir o perfilar algo más o abrir algún issue extra @vdeq79.

En iv.yaml creo que te has equivocado de path y faltaría meter el objeto valor anime. Y no entiendo muy bien lo que has hecho finalmente con titles.

2022-11-03 19:04 UTC, dmonjasm commented
Cierto, dejé el archivo iv.yaml con el path sin definir porque no estaba seguro de cual era la estructura de un proyecto en typescript. Por otro lado en titles si no me he equivocado se trata de un diccionario donde se recoge type que es de tipo string como clave y asociado a cada clave hay otro string.

Me basé en el json de #8 donde para los títulos se devolvía un diccionario con tipos (referiendose a los idiomas) y el correspondiente título en cada idioma. No sé si está correctamente declarado en TypeScript.

Voy a arreglar lo del iv.yaml y me comentas como ves lo de animes.ts.

2022-11-03 19:12 UTC, dmonjasm commented
Te mando el enlace donde obtuve la declaración. [Declaración dictionario](https://stackoverflow.com/questions/15877362/declare-and-initialize-a-dictionary-in-typescript)

2022-11-03 19:16 UTC, dmonjasm commented
> > No sé si quieres añadir o perfilar algo más o abrir algún issue extra @vdeq79.
> 
> En iv.yaml creo que te has equivocado de path y faltaría meter el objeto valor anime. Y no entiendo muy bien lo que has hecho finalmente con titles.

Por otro lado creo que los objetos valor no hay que ponerlos en el iv.yaml. Me parece que lo menciona en el README de la semana 7.

2022-11-03 20:09 UTC, vdeq79 commented
> > > No sé si quieres añadir o perfilar algo más o abrir algún issue extra @vdeq79.
> > 
> > 
> > En iv.yaml creo que te has equivocado de path y faltaría meter el objeto valor anime. Y no entiendo muy bien lo que has hecho finalmente con titles.
> 
> Por otro lado, creo que los objetos valor no hay que ponerlos en el iv.yaml. Me parece que lo menciona en el README de la semana 7.

Cierto, no lo había visto. Y lo del diccionario lo veía raro porque el clave lo has llamado _type_ como la otra variable de la clase. Por lo demás, lo veo todo correcto.

2022-11-03 20:13 UTC, vdeq79 submitted a review, later dismissed

2022-11-03 20:28 UTC, vdeq79 requested changes

2022-11-03 20:28 UTC, vdeq79 commented on src/user_list.ts
> +    animes_user: Anime[];
Aquí es posible que requeriría un cambio, por la convención de TypeScript (https://ts.dev/style/#identifiers) las variables deberían de usar lowerCamelCase, por lo tanto en este caso sería **animeUser**.

2022-11-03 22:10 UTC, dmonjasm commented on src/user_list.ts
> +    animes_user: Anime[];
Perfecto, mañana por la mañana lo arreglo que no tengo el ordenador a mano

2022-11-03 22:11 UTC, dmonjasm commented
> > > > No sé si quieres añadir o perfilar algo más o abrir algún issue extra @vdeq79.
> > > 
> > > 
> > > En iv.yaml creo que te has equivocado de path y faltaría meter el objeto valor anime. Y no entiendo muy bien lo que has hecho finalmente con titles.
> > 
> > 
> > Por otro lado, creo que los objetos valor no hay que ponerlos en el iv.yaml. Me parece que lo menciona en el README de la semana 7.
> 
> Cierto, no lo había visto. Y lo del diccionario lo veía raro porque el clave lo has llamado _type_ como la otra variable de la clase. Por lo demás, lo veo todo correcto.

Si quieres le cambio el nombre a language. Lo puse así por como lo llamaba el JSON, pero ciertamente da lugar a confusión.

2022-11-04 11:53 UTC, dmonjasm commented on src/user_list.ts
> +    animes_user: Anime[];
Acabo de subir los cambios.

2022-11-04 13:10 UTC, vdeq79 approved these changes

2022-11-04 14:28 UTC, dmonjasm commented
¿Algo más que veas que falta por arreglar o adaptar?, sino etiqueto a JJ para la revisión.

2022-11-04 14:51 UTC, vdeq79 commented
> ¿Algo más que veas que falta por arreglar o adaptar?, sino etiqueto a JJ para la revisión.

Adelante, nada que añadir de por mi parte.

2022-11-04 21:21 UTC, dmonjasm commented
Listo para revisión @JJ

2022-11-08 10:25 UTC, vdeq79 commented
Listo para revisión @JJ.

2022-11-08 10:41 UTC, JJ commented
> * [x]  ¿He seguido las mejores prácticas en nombre de las clases y ficheros y
>       disposición de los mismos?
> 
>     * [x]  ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
>       que se ha creado?
> 
>     * [x]  ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
>       una entidad o un agregado?
> 
>     * [x]  ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
>       objeto valor que no dependa de ningún otro (y que sea la base de muchos
>       otros)?.
> 
>     * [x]  ¿Los issues representan un problema, y no una tarea?
> 
>     * [x]  ¿Todos los mensajes de commit explican el cambio, y no se
>       limitan a repetir el nombre del fichero que se ha cambiado?
> 
>     * [x]  ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?

No, no lo siguen. "Avanza esto" o lo otro no aporta absolutamente nada.
> 
>     * [x]  ¿Se ha hecho una revisión real del código para comprobar que todos
>       los atributos y funciones creadas están respaldadas por una HU?
> 
>     * [x]  ¿Todos los issues creados están asignados a una HU?
> 
No, no lo están. No marquéis cosas que no habéis hecho. Sólo añadís trabajo a la persona que corrige.

>     * [x]  ¿Se ha comprobado que el código entregado sea sintácticamente
>       correcto?

¿Cómo se ha comprobado esto?

2022-11-08 10:42 UTC, JJ commented
Si no se ha seguido la metodología, no es correcto el desarrollo. Por favor, mirad [los errores frecuentes](https://github.com/JJ/IV-22-23/blob/master/sesiones/semana-08.md#objetivo-2) y, sobre todo, no marquéis items de la lista de comprobación que sean incorrectos.

2022-11-14 08:30 UTC, JJ commented
¿Qué falta aquí?

2022-11-14 08:50 UTC, dmonjasm commented
Voy a documentar en el README la elección de entidades y objetos valor, así como una explicación de cómo se ha comprobado el código y ampliar este un poco.

2022-11-21 21:35 UTC, dmonjasm commented
He añadido documentación de la elección de los objetos valor y las entidades en el README. También he añadido un análisis del dominio en el README. Finalmente, he declarado e inicializado variables de tipo anime y user_list y he compilado con deno para ver si habían errores de sintaxis.

2022-11-21 21:36 UTC, dmonjasm commented
@vdeq79 échale cuando puedas un ojo a los cambios a ver que te parecen.

2022-11-22 10:17 UTC, vdeq79 commented on src/anime.ts
> +
Sí creo que es relevante como comenté en #8 tener almacenado los studios que han trabajado en la serie para utilizarlos en la lógica de negocio. Y como comenté en #7, es necesario tener una forma de determinar los estados del anime para el usuario (estados como por ejemplo: viendo, completado, pendiente, abandonad..) .

2022-11-22 10:22 UTC, dmonjasm commented on src/anime.ts
> +
De acuerdo entonces elimino sinopsis y Broadcast y le añado un campo para los estudios y otro para el estado

2022-11-23 11:11 UTC, dmonjasm commented
Hechas las modificaciones pedidas. Échale un ojo y me dices @vdeq79.

2022-11-23 17:45 UTC, vdeq79 approved these changes

2022-11-23 17:46 UTC, vdeq79 commented
Creo que esta listo para revisión @JJ.

2022-11-23 17:57 UTC, JJ commented
> * [x]  ¿He seguido las mejores prácticas en nombre de las clases y ficheros y
>       disposición de los mismos?
> 
>     * [x]  ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
>       que se ha creado?
> 

¿Dónde está esto documentado?

>     * [x]  ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
>       una entidad o un agregado?

¿Dónde?

2022-11-23 18:03 UTC, dmonjasm commented
En el README

2022-11-23 18:04 UTC, JJ commented
> > * [x]  ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
> > ```
> 
> No, no lo siguen. "Avanza esto" o lo otro no aporta absolutamente nada.

Siguen sin seguir las mejores prácticas, al menos en la longitud de la primera línea: https://github.com/vdeq79/Projecto-XSZ/pull/14/commits/1ad83424053bb42611a755501c627755c2f97b82 https://github.com/vdeq79/Projecto-XSZ/pull/14/commits/bd8a0b671430971c47c0ba3ebd3a4140f7fd88da

2022-11-23 18:05 UTC, JJ commented
> En el README

OK, ya lo veo, perdona.

2022-11-23 18:09 UTC, JJ requested changes
Los ejemplos no forman parte de un PMV y no es la mejor práctica incluirlos en el código de una clase.

2022-11-23 18:09 UTC, JJ commented on README.md
> +- Synopsis: se trata de una descripción del anime en cuestión.
Esto no hace falta que lo describas. Además, se supone que lo habías quitado, ¿no?

2022-11-23 18:09 UTC, JJ commented on src/user_list.ts
> +let anime = new Anime({'English': 'Demon Slayer'},
No puedes poner un ejemplo. Primero, porque no lo pide el PMV. Segundo, porque es incorrecto.

2022-11-23 18:09 UTC, JJ commented on src/anime.ts
> +let anime = new Anime({'English': 'Demon Slayer'},
No puedes poner ejemplos.

2022-11-23 18:12 UTC, dmonjasm commented on README.md
> +- Synopsis: se trata de una descripción del anime en cuestión.
Cierto al cambiar los atributos no he revisado el análisis. Lo corrijo

2022-11-23 18:13 UTC, dmonjasm commented on src/user_list.ts
> +let anime = new Anime({'English': 'Demon Slayer'},
Lo puse para probar la compilación con deno pero también lo quito

2022-11-23 18:31 UTC, dmonjasm commented on README.md
> +- Synopsis: se trata de una descripción del anime en cuestión.
Corregido.

2022-11-23 18:31 UTC, dmonjasm commented on src/user_list.ts
> +let anime = new Anime({'English': 'Demon Slayer'},
Corregido.

2022-11-23 18:31 UTC, dmonjasm commented on src/anime.ts
> +let anime = new Anime({'English': 'Demon Slayer'},
Corregido.

2022-11-23 18:36 UTC, JJ approved these changes
:+1:

2022-11-23 18:39 UTC, dmonjasm commented
Una pregunta. @vdeq79 ya ha aprobado el objetivo 3 con el correspondiente merge que esto implica. Por tanto me salen conflictos con lo que el tiene actualmente en su rama main. ¿Resuelvo los conflictos o descarto los commits?

2022-11-23 18:43 UTC, JJ commented
No, eso ya es cosa de él, mergearlo o lo que sea. Por tu parte has superado el objetivo.

2022-11-23 18:43 UTC, dmonjasm commented
Perfecto, gracias.

2022-11-23 20:50 UTC, merged