[IV-22-23] Objetivo 5
vdeq79/Projecto-XSZ pull request #26
Opened 2022-12-11 16:11 UTC by vdeq79

2022-12-13 21:57 UTC, vdeq79 commented
Listo para revisión @JJ.

2022-12-13 22:01 UTC, vdeq79 commented
Listo para revisión @JJ.

2022-12-14 08:16 UTC, JJ requested changes
Por favor, sigue las buenas prácticas en la creación de las imágenes Docker y trata de seguri criterios con más relevancia.

2022-12-14 08:16 UTC, JJ commented on Dockerfile
> +RUN pnpm install -g grunt-cli
¿Por qué usas dos comandos?

2022-12-14 08:16 UTC, JJ commented on Dockerfile
> +RUN chown -R 1001 /app
Una de las buenas prácticas en los Dockerfile es que tengan un usuario no privilegiado. Por favor, o lo creas o investigas si el contenedor base lo tiene y en ese caso lo usas. 1001 es sólo un usuario de GitHub actions, y no tienes garantizado que tenga ese UID, porque no es un API publicado.

2022-12-14 08:16 UTC, JJ commented on docs/documentations/imagen-base.md
> +- [**ianwalter/pnpm**](https://hub.docker.com/r/ianwalter/pnpm): imagen base que contiene node y pnpm, sin embargo, las versiones se encuentran desactualizadas con la versión de node en 14.15.1 y la
Pues hazles un PR.

2022-12-14 08:16 UTC, JJ commented on docs/documentations/imagen-base.md
> +- Tiempo que tarda en ejecutar los tests.
La principal es siempre el tamaño de la imagen.

2022-12-14 08:16 UTC, JJ commented on docs/documentations/imagen-base.md
> +- [**node**](https://hub.docker.com/_/node): imagen oficial de node.js con sus últimas actualizaciones.
¿Qué tamaño tiene?

2022-12-14 08:16 UTC, JJ commented on docs/documentations/imagen-base.md
> +Tras probar con las tres imágenes, se ha comprobado que tardan lo mismo en ejecutar los tests (ya que todos utilizan como base a node) y por ser la imagen de node la que posee la versión más actualiz
pero ¿cuanto tardan en descargarse?

2022-12-14 10:22 UTC, JJ commented on Dockerfile
> +RUN pnpm install -g grunt-cli
Creo que en las últimas versiones ya no es necesario, pero lo cierto es que estás usando dos comandos diferentes cuando podrías usar uno.

2022-12-14 11:03 UTC, vdeq79 commented on Dockerfile
> +RUN chown -R 1001 /app
La imagen base de node ya tiene un usuario genérico **node** con UID 1000, pero en este caso como el usuario que usamos tiene username o UID 1001 ([según la documentación de docker run](https://docs.docker.com/engine/reference/commandline/run/)), ¿habría crearla igualmente no?

2022-12-14 11:14 UTC, JJ commented on Dockerfile
> +RUN chown -R 1001 /app
No. Ya os he dicho en el guión que no tienes que asumir que tienes derecho de escritura en el directorio montado. Primero, por higiene (ahí están las fuentes y puedes cargarte algo). Segundo, porque te lo dice. Y tercero, porque no está documentado que se trate de ese UID y por tanto puede cambiar perfectamente. Tampoco vas a desarrollar esto para GitHub actions, el Dockerfile puede evolucionarse para trabajar en cualquier otro entorno. En general, es mala práctica diseñar algo con suposiciones sobre dónde se va ejecutar, y mucho más si no forman parte del API oficial.

2022-12-14 11:51 UTC, vdeq79 commented
Listo para revisión @JJ.

2022-12-14 12:07 UTC, vdeq79 commented
Listo para revisión @JJ.

2022-12-14 18:58 UTC, JJ requested changes
Creo que no has examinado bien las consecuencias de las decisiones que has tomado. También conviene una vez más que prestes atención a lo que estás haciendo realmente a la hora de construir la imagen.

2022-12-14 18:58 UTC, JJ commented on Dockerfile
> +FROM node:19.2.0-alpine
Por qué usas
1. ¿una versión que no tiene soporte de larga duración?
2. ¿una versión específica con los tres números en vez de una versión *major* simplemente?

2022-12-14 18:58 UTC, JJ commented on Dockerfile
> +RUN npm install --global pnpm && pnpm install -g grunt-cli
Creo que no me has entendido. ¿De veras hace falta que instales cada cosa con un comando diferente? ¿No puedes instalar las dos cosas con el mismo comando?

2022-12-14 18:58 UTC, JJ commented on Dockerfile
> +RUN pnpm install
¿Con qué usuario estás ejecutando estas órdenes?

2022-12-14 18:58 UTC, JJ commented on Dockerfile
> +#Cambiar el usuario de la imagen
¿Aquí?

2022-12-14 18:58 UTC, JJ commented on Dockerfile
> +CMD [ "test" ]
¿No puedes ponerlo en una sola orden?

2022-12-14 18:58 UTC, JJ commented on docs/documentations/imagen-base.md
> +Para la elección de la imagen base siguiendo las mejores prácticas, los criterios que se tienen en cuenta son los siguientes:
Tendrás que elegir primero la versión, y ser muy consciente, en función de la versión, qué es lo que estás testeando.

2022-12-14 18:58 UTC, JJ commented on docs/documentations/imagen-base.md
> +Siguiendo las buenas prácticas, usaremos la imagen oficial de [**node**](https://hub.docker.com/_/node) con la versión actual 19.2.0, pero para minimizar el tamaño se ha descargado la imagen con dife
Es la versión de desarrollo actual, pero sólo en este momento. Tienes que ser consciente de qué es lo que estás eligiendo, si la estable o de desarrollo, y si es una versión específica (como esta) o la última versión de esa *major* que estés usando.

2022-12-15 13:02 UTC, vdeq79 commented
Listo para revisión @JJ.

2022-12-15 15:43 UTC, vdeq79 commented
Listo para revisión @JJ.

2022-12-15 16:42 UTC, JJ approved these changes
👍

2022-12-16 09:51 UTC, merged