[IV-22-23] Objetivo 5
vdeq79/Projecto-XSZ pull request #30
Opened 2022-12-26 10:52 UTC by vdeq79

* [ ] ¿Se ha evitado Circle CI, porque a estas alturas ya lo ha usado todo el mundo?
* [ ] ¿Se han establecido criterios *a priori* para elegir el sistema de integración continua más conveniente y se han calificado los sistemas que cumplan esos requisitos según esos criterios?
* [ ] ¿Se han examinado varios sistemas de integración continua?
* [ ] ¿Se han configurado varios sistemas de integración continua?
* [ ] ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar desde los tests)?
* [ ] ¿Uno de los sistemas configurados permite comprobar cuales son las versiones del lenguaje con las que funciona correctamente nuestra aplicación?
* [ ] ¿Se escogen de forma adecuada las versiones del lenguaje que se testean, tanto en el sistema de CI como en el contenedor Docker?
* [ ] ¿Se han justificado correctamente las versiones del lenguaje que se están testeando y se ha comprobado que no se comprueban varias veces lo mismo (la misma versión en CI y en el contenedor Docker en otro sistema CI)?

2022-12-27 09:36 UTC, vdeq79 commented
Listo para revisión @JJ.

2022-12-28 09:19 UTC, JJ requested changes
El único obstáculo es que compruebes que no estás testeando dos veces lo mismo. ¿Qué versión del lenguaje se usa en la imagen Docker?

2022-12-28 12:25 UTC, vdeq79 commented
> El único obstáculo es que compruebes que no estás testeando dos veces lo mismo. ¿Qué versión del lenguaje se usa en la imagen Docker?

En la imagen Docker utilizo **lts**, que se actualiza conforme node.js saque nuevas versiones estables. Y en Github Action testeo las versiones latest, 14, 16 y 18. Esto lo tengo documentado en #29.

2022-12-28 13:35 UTC, JJ commented
> > El único obstáculo es que compruebes que no estás testeando dos veces lo mismo. ¿Qué versión del lenguaje se usa en la imagen Docker?
> 
> En la imagen Docker utilizo **lts**, que se actualiza conforme node.js saque nuevas versiones estables. Y en Github Action testeo las versiones latest, 14, 16 y 18. Esto lo tengo documentado en #29.

¿Alguna de esas versiones coincidirá con la lts? Es lo que te estoy preguntando.

2022-12-28 13:57 UTC, vdeq79 commented
> > > El único obstáculo es que compruebes que no estás testeando dos veces lo mismo. ¿Qué versión del lenguaje se usa en la imagen Docker?
> > 
> > 
> > En la imagen Docker utilizo **lts**, que se actualiza conforme node.js saque nuevas versiones estables. Y en Github Action testeo las versiones latest, 14, 16 y 18. Esto lo tengo documentado en #29.
> 
> ¿Alguna de esas versiones coincidirá con la lts? Es lo que te estoy preguntando.

El 18 coincide actualmente con la lts, lo había puesto pensando que la lts podría actualizarse en un futuro y pasar a otra versión (la 20 por ejemplo). ¿Lo elimino para no generar cargas técnicas?

2022-12-28 18:38 UTC, JJ commented
> > > > El único obstáculo es que compruebes que no estás testeando dos veces lo mismo. ¿Qué versión del lenguaje se usa en la imagen Docker?
> > > 
> > > 
> > > En la imagen Docker utilizo **lts**, que se actualiza conforme node.js saque nuevas versiones estables. Y en Github Action testeo las versiones latest, 14, 16 y 18. Esto lo tengo documentado en #29.
> > 
> > 
> > ¿Alguna de esas versiones coincidirá con la lts? Es lo que te estoy preguntando.
> 
> La 18 coincide actualmente con la lts, lo había puesto pensando que la lts podría actualizarse en un futuro y pasar a otra versión (la 20 por ejemplo). ¿La elimino para no generar cargas técnicas?

Os dije en clase que no tenía sentido que repitiérais el test con la misma configuración dos veces. A partir de ahí, haz lo que consideres conveniente.

2022-12-28 19:20 UTC, vdeq79 commented
Listo para revisión @JJ.

2022-12-28 19:25 UTC, JJ requested changes
Covendría que no os quedárais con el detalle y mirárais el principio: no se testea dos veces con la misma configuración, y hay que testear un rango amplio de configuraciones que incluya la de desarrollo.

2022-12-28 19:25 UTC, JJ commented on .github/workflows/CI-test.yml
> +        node-version: ['14', '16', 'latest']
Vuelvo a decirte que es una pérdida de tiempo testear las cosas dos veces. ¿Qué versión es la `latest`?
También ¿por qué no testeas la versión de desarrollo? ¿No os dije en clase que era una de las versiones que teníais que testear?

2022-12-28 19:42 UTC, vdeq79 commented on .github/workflows/CI-test.yml
> +        node-version: ['14', '16', 'latest']
Creo que latest es la versión de desarrollo de node, es decir, la 19.3.0.
![latest](https://user-images.githubusercontent.com/101350015/209863863-7e00bc3c-840b-4a97-8681-1edc92204440.png)

2022-12-28 19:53 UTC, JJ commented on .github/workflows/CI-test.yml
> +        node-version: ['14', '16', 'latest']
¿lo has documentado así?

2022-12-28 20:06 UTC, vdeq79 commented on .github/workflows/CI-test.yml
> +        node-version: ['14', '16', 'latest']
No sé a que se refiere, desde el objetivo anterior había visto que latest hacía referencia a la última versión y lts es la versión estable actual (por lo que lo elegí para Docker).

2022-12-29 08:20 UTC, JJ commented on .github/workflows/CI-test.yml
> +        node-version: ['14', '16', 'latest']
A que debes ponerlo en la documentación del objetivo.

2022-12-29 09:57 UTC, vdeq79 commented on .github/workflows/CI-test.yml
> +        node-version: ['14', '16', 'latest']
Añadido a la documentación:ok_hand:.

2022-12-29 10:12 UTC, JJ approved these changes
:+1:

2022-12-29 10:18 UTC, merged